"""Canonical normalization layer."""

from findupdates.normalization.models import (
    PARSER_VERSION,
    SCHEMA_VERSION,
    AffectedProduct,
    Architecture,
    Completeness,
    Confidence,
    Conflict,
    CvssRecord,
    CvssVersion,
    Exploitability,
    FieldProvenance,
    NormalizedSourceRecord,
    PackageId,
    PackageKind,
    ProductStatus,
    Provenance,
    RebootRequirement,
    Remediation,
    RemediationKind,
    TriState,
    UpdateAdvisory,
    UpdateCategory,
    Vendor,
    VendorSeverity,
    completeness_for,
    incomplete_fields_for,
    logical_advisory_key,
    merge_advisories,
    normalize_source_record,
)
from findupdates.normalization.serialize import advisory_to_dict, canonical_json

__all__ = [
    "PARSER_VERSION",
    "SCHEMA_VERSION",
    "AffectedProduct",
    "Architecture",
    "Completeness",
    "Confidence",
    "Conflict",
    "CvssRecord",
    "CvssVersion",
    "Exploitability",
    "FieldProvenance",
    "NormalizedSourceRecord",
    "PackageId",
    "PackageKind",
    "ProductStatus",
    "Provenance",
    "RebootRequirement",
    "Remediation",
    "RemediationKind",
    "TriState",
    "UpdateAdvisory",
    "UpdateCategory",
    "Vendor",
    "VendorSeverity",
    "advisory_to_dict",
    "canonical_json",
    "completeness_for",
    "incomplete_fields_for",
    "logical_advisory_key",
    "merge_advisories",
    "normalize_source_record",
]
